# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatClient.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1222, 900)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(46, 46, 46);")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.displayHello = QtWidgets.QLabel(self.centralwidget)
        self.displayHello.setGeometry(QtCore.QRect(20, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.displayHello.setFont(font)
        self.displayHello.setStyleSheet("color:rgb(255, 173, 152)")
        self.displayHello.setObjectName("displayHello")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 480, 1190, 3))
        self.line.setStyleSheet("background-color: rgb(249,38,114);")
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(210, 490, 3, 401))
        self.line_3.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 500, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 580, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 750, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 670, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 830, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_11.setObjectName("label_11")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 640, 191, 3))
        self.line_4.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 550, 191, 3))
        self.line_5.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 730, 191, 3))
        self.line_6.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(10, 810, 191, 3))
        self.line_7.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.read_p = QtWidgets.QLineEdit(self.centralwidget)
        self.read_p.setGeometry(QtCore.QRect(350, 490, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.read_p.setFont(font)
        self.read_p.setStyleSheet("color: rgb(249,38,114);")
        self.read_p.setText("")
        self.read_p.setObjectName("read_p")
        self.set_p = QtWidgets.QPushButton(self.centralwidget)
        self.set_p.setGeometry(QtCore.QRect(220, 490, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.set_p.setFont(font)
        self.set_p.setStyleSheet("color: rgb(253,151,31);")
        self.set_p.setObjectName("set_p")
        self.set_q = QtWidgets.QPushButton(self.centralwidget)
        self.set_q.setGeometry(QtCore.QRect(220, 550, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.set_q.setFont(font)
        self.set_q.setStyleSheet("color: rgb(253,151,31);")
        self.set_q.setObjectName("set_q")
        self.read_q = QtWidgets.QLineEdit(self.centralwidget)
        self.read_q.setGeometry(QtCore.QRect(350, 550, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.read_q.setFont(font)
        self.read_q.setStyleSheet("color: rgb(249,38,114);")
        self.read_q.setText("")
        self.read_q.setObjectName("read_q")
        self.messageFromSystem = QtWidgets.QLineEdit(self.centralwidget)
        self.messageFromSystem.setGeometry(QtCore.QRect(150, 70, 1051, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.messageFromSystem.setFont(font)
        self.messageFromSystem.setAccessibleDescription("")
        self.messageFromSystem.setStyleSheet("color: rgb(249,38,114);")
        self.messageFromSystem.setText("")
        self.messageFromSystem.setObjectName("messageFromSystem")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(220, 600, 301, 3))
        self.line_11.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(530, 490, 3, 401))
        self.line_10.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.displayHello_2 = QtWidgets.QLabel(self.centralwidget)
        self.displayHello_2.setGeometry(QtCore.QRect(620, 500, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.displayHello_2.setFont(font)
        self.displayHello_2.setStyleSheet("color:rgb(255, 173, 152)")
        self.displayHello_2.setObjectName("displayHello_2")
        self.set_your_port = QtWidgets.QPushButton(self.centralwidget)
        self.set_your_port.setGeometry(QtCore.QRect(220, 770, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.set_your_port.setFont(font)
        self.set_your_port.setStyleSheet("color: rgb(253,151,31);")
        self.set_your_port.setObjectName("set_your_port")
        self.read_your_port = QtWidgets.QLineEdit(self.centralwidget)
        self.read_your_port.setGeometry(QtCore.QRect(430, 770, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.read_your_port.setFont(font)
        self.read_your_port.setStyleSheet("color: rgb(249,38,114);")
        self.read_your_port.setText("")
        self.read_your_port.setObjectName("read_your_port")
        self.generateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.generateKeys.setGeometry(QtCore.QRect(220, 820, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generateKeys.setFont(font)
        self.generateKeys.setStyleSheet("color: rgb(253,151,31);")
        self.generateKeys.setObjectName("generateKeys")
        self.generateCertificate = QtWidgets.QPushButton(self.centralwidget)
        self.generateCertificate.setGeometry(QtCore.QRect(220, 860, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generateCertificate.setFont(font)
        self.generateCertificate.setStyleSheet("color: rgb(253,151,31);")
        self.generateCertificate.setObjectName("generateCertificate")
        self.read_server_port = QtWidgets.QLineEdit(self.centralwidget)
        self.read_server_port.setGeometry(QtCore.QRect(430, 720, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.read_server_port.setFont(font)
        self.read_server_port.setStyleSheet("color: rgb(249,38,114);")
        self.read_server_port.setText("")
        self.read_server_port.setObjectName("read_server_port")
        self.set_server_port = QtWidgets.QPushButton(self.centralwidget)
        self.set_server_port.setGeometry(QtCore.QRect(220, 720, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.set_server_port.setFont(font)
        self.set_server_port.setStyleSheet("color: rgb(253,151,31);")
        self.set_server_port.setObjectName("set_server_port")
        self.set_name = QtWidgets.QPushButton(self.centralwidget)
        self.set_name.setGeometry(QtCore.QRect(270, 660, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.set_name.setFont(font)
        self.set_name.setStyleSheet("color: rgb(253,151,31);")
        self.set_name.setObjectName("set_name")
        self.read_name = QtWidgets.QLineEdit(self.centralwidget)
        self.read_name.setGeometry(QtCore.QRect(220, 610, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(14)
        self.read_name.setFont(font)
        self.read_name.setStyleSheet("color: rgb(249,38,114);")
        self.read_name.setText("")
        self.read_name.setObjectName("read_name")
        self.displayCertificate_ID_CA = QtWidgets.QLineEdit(self.centralwidget)
        self.displayCertificate_ID_CA.setGeometry(QtCore.QRect(650, 810, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.displayCertificate_ID_CA.setFont(font)
        self.displayCertificate_ID_CA.setStyleSheet("color: rgb(249,38,114);")
        self.displayCertificate_ID_CA.setText("")
        self.displayCertificate_ID_CA.setObjectName("displayCertificate_ID_CA")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(550, 810, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(550, 750, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(550, 690, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(550, 630, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_19.setObjectName("label_19")
        self.displayCertificate_Time = QtWidgets.QLineEdit(self.centralwidget)
        self.displayCertificate_Time.setGeometry(QtCore.QRect(630, 690, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.displayCertificate_Time.setFont(font)
        self.displayCertificate_Time.setStyleSheet("color: rgb(249,38,114);")
        self.displayCertificate_Time.setText("")
        self.displayCertificate_Time.setObjectName("displayCertificate_Time")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(550, 570, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_20.setObjectName("label_20")
        self.displayCertificate_PU_A = QtWidgets.QLineEdit(self.centralwidget)
        self.displayCertificate_PU_A.setGeometry(QtCore.QRect(630, 630, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.displayCertificate_PU_A.setFont(font)
        self.displayCertificate_PU_A.setStyleSheet("color: rgb(249,38,114);")
        self.displayCertificate_PU_A.setText("")
        self.displayCertificate_PU_A.setObjectName("displayCertificate_PU_A")
        self.displayCertificate_Duration = QtWidgets.QLineEdit(self.centralwidget)
        self.displayCertificate_Duration.setGeometry(QtCore.QRect(670, 750, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.displayCertificate_Duration.setFont(font)
        self.displayCertificate_Duration.setStyleSheet("color: rgb(249,38,114);")
        self.displayCertificate_Duration.setText("")
        self.displayCertificate_Duration.setObjectName("displayCertificate_Duration")
        self.displayCertificate_IDA = QtWidgets.QLineEdit(self.centralwidget)
        self.displayCertificate_IDA.setGeometry(QtCore.QRect(620, 570, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.displayCertificate_IDA.setFont(font)
        self.displayCertificate_IDA.setStyleSheet("color: rgb(249,38,114);")
        self.displayCertificate_IDA.setText("")
        self.displayCertificate_IDA.setObjectName("displayCertificate_IDA")
        self.setPort_B = QtWidgets.QPushButton(self.centralwidget)
        self.setPort_B.setGeometry(QtCore.QRect(80, 130, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.setPort_B.setFont(font)
        self.setPort_B.setStyleSheet("color: rgb(253,151,31);")
        self.setPort_B.setObjectName("setPort_B")
        self.read_port_B = QtWidgets.QLineEdit(self.centralwidget)
        self.read_port_B.setGeometry(QtCore.QRect(230, 130, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.read_port_B.setFont(font)
        self.read_port_B.setStyleSheet("color: rgb(249,38,114);")
        self.read_port_B.setText("")
        self.read_port_B.setObjectName("read_port_B")
        self.read_ID_B = QtWidgets.QLineEdit(self.centralwidget)
        self.read_ID_B.setGeometry(QtCore.QRect(650, 130, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.read_ID_B.setFont(font)
        self.read_ID_B.setStyleSheet("color: rgb(249,38,114);")
        self.read_ID_B.setText("")
        self.read_ID_B.setObjectName("read_ID_B")
        self.set_ID_B = QtWidgets.QPushButton(self.centralwidget)
        self.set_ID_B.setGeometry(QtCore.QRect(520, 130, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.set_ID_B.setFont(font)
        self.set_ID_B.setStyleSheet("color: rgb(253,151,31);")
        self.set_ID_B.setObjectName("set_ID_B")
        self.getCertificateOfB = QtWidgets.QPushButton(self.centralwidget)
        self.getCertificateOfB.setGeometry(QtCore.QRect(60, 180, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.getCertificateOfB.setFont(font)
        self.getCertificateOfB.setStyleSheet("color: rgb(253,151,31);")
        self.getCertificateOfB.setObjectName("getCertificateOfB")
        self.verifyCertificateOfB = QtWidgets.QPushButton(self.centralwidget)
        self.verifyCertificateOfB.setGeometry(QtCore.QRect(510, 180, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.verifyCertificateOfB.setFont(font)
        self.verifyCertificateOfB.setStyleSheet("color: rgb(253,151,31);")
        self.verifyCertificateOfB.setObjectName("verifyCertificateOfB")
        self.chatWindow = QtWidgets.QTextEdit(self.centralwidget)
        self.chatWindow.setGeometry(QtCore.QRect(30, 230, 1181, 181))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(14)
        self.chatWindow.setFont(font)
        self.chatWindow.setStyleSheet("color: rgb(249,38,114);")
        self.chatWindow.setObjectName("chatWindow")
        self.connectToB = QtWidgets.QPushButton(self.centralwidget)
        self.connectToB.setGeometry(QtCore.QRect(920, 150, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.connectToB.setFont(font)
        self.connectToB.setStyleSheet("color: rgb(253,151,31);")
        self.connectToB.setObjectName("connectToB")
        self.display_p = QtWidgets.QLineEdit(self.centralwidget)
        self.display_p.setGeometry(QtCore.QRect(60, 500, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.display_p.setFont(font)
        self.display_p.setStyleSheet("color: rgb(249,38,114);")
        self.display_p.setText("")
        self.display_p.setObjectName("display_p")
        self.display_q = QtWidgets.QLineEdit(self.centralwidget)
        self.display_q.setGeometry(QtCore.QRect(60, 580, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.display_q.setFont(font)
        self.display_q.setStyleSheet("color: rgb(249,38,114);")
        self.display_q.setText("")
        self.display_q.setObjectName("display_q")
        self.display_e = QtWidgets.QLineEdit(self.centralwidget)
        self.display_e.setGeometry(QtCore.QRect(60, 670, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.display_e.setFont(font)
        self.display_e.setStyleSheet("color: rgb(249,38,114);")
        self.display_e.setText("")
        self.display_e.setObjectName("display_e")
        self.display_d = QtWidgets.QLineEdit(self.centralwidget)
        self.display_d.setGeometry(QtCore.QRect(60, 750, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.display_d.setFont(font)
        self.display_d.setStyleSheet("color: rgb(249,38,114);")
        self.display_d.setText("")
        self.display_d.setObjectName("display_d")
        self.display_n = QtWidgets.QLineEdit(self.centralwidget)
        self.display_n.setGeometry(QtCore.QRect(60, 830, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.display_n.setFont(font)
        self.display_n.setStyleSheet("color: rgb(249,38,114);")
        self.display_n.setText("")
        self.display_n.setObjectName("display_n")
        self.start_listening = QtWidgets.QPushButton(self.centralwidget)
        self.start_listening.setGeometry(QtCore.QRect(990, 0, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.start_listening.setFont(font)
        self.start_listening.setStyleSheet("color: rgb(253,151,31);")
        self.start_listening.setObjectName("start_listening")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(600, 0, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_21.setObjectName("label_21")
        self.display_Connection_status = QtWidgets.QLineEdit(self.centralwidget)
        self.display_Connection_status.setGeometry(QtCore.QRect(680, 0, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.display_Connection_status.setFont(font)
        self.display_Connection_status.setStyleSheet("color: rgb(249,38,114);")
        self.display_Connection_status.setObjectName("display_Connection_status")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(20, 420, 1190, 3))
        self.line_13.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(20, 220, 1190, 3))
        self.line_14.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_14.setLineWidth(2)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(20, 110, 1190, 3))
        self.line_15.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(20, 50, 1190, 3))
        self.line_16.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_16.setLineWidth(2)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.displayHello_3 = QtWidgets.QLabel(self.centralwidget)
        self.displayHello_3.setGeometry(QtCore.QRect(20, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.displayHello_3.setFont(font)
        self.displayHello_3.setStyleSheet("color:rgb(255, 173, 152)")
        self.displayHello_3.setObjectName("displayHello_3")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(920, 810, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_22.setObjectName("label_22")
        self.displayCertificate_IDB = QtWidgets.QLineEdit(self.centralwidget)
        self.displayCertificate_IDB.setGeometry(QtCore.QRect(990, 570, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.displayCertificate_IDB.setFont(font)
        self.displayCertificate_IDB.setStyleSheet("color: rgb(249,38,114);")
        self.displayCertificate_IDB.setText("")
        self.displayCertificate_IDB.setObjectName("displayCertificate_IDB")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(920, 690, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_23.setObjectName("label_23")
        self.displayCertificate_Duration_B = QtWidgets.QLineEdit(self.centralwidget)
        self.displayCertificate_Duration_B.setGeometry(QtCore.QRect(1040, 750, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.displayCertificate_Duration_B.setFont(font)
        self.displayCertificate_Duration_B.setStyleSheet("color: rgb(249,38,114);")
        self.displayCertificate_Duration_B.setText("")
        self.displayCertificate_Duration_B.setObjectName("displayCertificate_Duration_B")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(920, 630, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_24.setObjectName("label_24")
        self.displayHello_4 = QtWidgets.QLabel(self.centralwidget)
        self.displayHello_4.setGeometry(QtCore.QRect(920, 500, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.displayHello_4.setFont(font)
        self.displayHello_4.setStyleSheet("color:rgb(255, 173, 152)")
        self.displayHello_4.setObjectName("displayHello_4")
        self.displayCertificate_ID_CA_B = QtWidgets.QLineEdit(self.centralwidget)
        self.displayCertificate_ID_CA_B.setGeometry(QtCore.QRect(1000, 810, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.displayCertificate_ID_CA_B.setFont(font)
        self.displayCertificate_ID_CA_B.setStyleSheet("color: rgb(249,38,114);")
        self.displayCertificate_ID_CA_B.setText("")
        self.displayCertificate_ID_CA_B.setObjectName("displayCertificate_ID_CA_B")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(920, 750, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_25.setObjectName("label_25")
        self.displayCertificate_Time_B = QtWidgets.QLineEdit(self.centralwidget)
        self.displayCertificate_Time_B.setGeometry(QtCore.QRect(990, 690, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.displayCertificate_Time_B.setFont(font)
        self.displayCertificate_Time_B.setStyleSheet("color: rgb(249,38,114);")
        self.displayCertificate_Time_B.setText("")
        self.displayCertificate_Time_B.setObjectName("displayCertificate_Time_B")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(920, 570, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color:rgb(255, 173, 152)")
        self.label_26.setObjectName("label_26")
        self.displayCertificate_PU_B = QtWidgets.QLineEdit(self.centralwidget)
        self.displayCertificate_PU_B.setGeometry(QtCore.QRect(1000, 630, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        self.displayCertificate_PU_B.setFont(font)
        self.displayCertificate_PU_B.setStyleSheet("color: rgb(249,38,114);")
        self.displayCertificate_PU_B.setText("")
        self.displayCertificate_PU_B.setObjectName("displayCertificate_PU_B")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(900, 490, 3, 401))
        self.line_12.setStyleSheet("background-color: rgb(249,38,114);")
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.displayHello_5 = QtWidgets.QLabel(self.centralwidget)
        self.displayHello_5.setGeometry(QtCore.QRect(280, 440, 601, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.displayHello_5.setFont(font)
        self.displayHello_5.setStyleSheet("color:rgb(255, 173, 152)")
        self.displayHello_5.setObjectName("displayHello_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat Client"))
        self.displayHello.setText(_translate("MainWindow", "Hello unknown"))
        self.label_7.setText(_translate("MainWindow", "p"))
        self.label_8.setText(_translate("MainWindow", "q"))
        self.label_9.setText(_translate("MainWindow", "d"))
        self.label_10.setText(_translate("MainWindow", "e"))
        self.label_11.setText(_translate("MainWindow", "n"))
        self.set_p.setText(_translate("MainWindow", "Set p"))
        self.set_q.setText(_translate("MainWindow", "Set q"))
        self.displayHello_2.setText(_translate("MainWindow", "Your Certificate"))
        self.set_your_port.setText(_translate("MainWindow", "Your Port number"))
        self.generateKeys.setText(_translate("MainWindow", "Generate Keys"))
        self.generateCertificate.setText(_translate("MainWindow", "Get Certificate"))
        self.set_server_port.setText(_translate("MainWindow", "Server Port number"))
        self.set_name.setText(_translate("MainWindow", "Enter name"))
        self.label_16.setText(_translate("MainWindow", "ID_CA"))
        self.label_17.setText(_translate("MainWindow", "Duration"))
        self.label_18.setText(_translate("MainWindow", "Time"))
        self.label_19.setText(_translate("MainWindow", "PU_A"))
        self.label_20.setText(_translate("MainWindow", "ID_A"))
        self.setPort_B.setText(_translate("MainWindow", "Port of B"))
        self.set_ID_B.setText(_translate("MainWindow", "ID of B"))
        self.getCertificateOfB.setText(_translate("MainWindow", "Get Certificate of B"))
        self.verifyCertificateOfB.setText(_translate("MainWindow", "Verify Certificate of B"))
        self.chatWindow.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.connectToB.setText(_translate("MainWindow", "Connect to B"))
        self.start_listening.setText(_translate("MainWindow", "Go online"))
        self.label_21.setText(_translate("MainWindow", "Status"))
        self.display_Connection_status.setText(_translate("MainWindow", "Offline"))
        self.displayHello_3.setText(_translate("MainWindow", "System : "))
        self.label_22.setText(_translate("MainWindow", "ID_CA"))
        self.label_23.setText(_translate("MainWindow", "Time"))
        self.label_24.setText(_translate("MainWindow", "PU_B"))
        self.displayHello_4.setText(_translate("MainWindow", "Other\'s Certificate"))
        self.label_25.setText(_translate("MainWindow", "Duration"))
        self.label_26.setText(_translate("MainWindow", "ID_B"))
        self.displayHello_5.setText(_translate("MainWindow", "Possible primes are : 229, 233, 239, 241 ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
